[env:seeed_xiao_esp32c6]
platform = espressif32
board = seeed_xiao_esp32c6
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
lib_deps =
    knolleary/PubSubClient@^2.8
    h2zero/NimBLE-Arduino@^2.0.0